version: "3"
volumes:
  home:
  src:
  opt:
services:
  devenv:
    build:
      context: .
    volumes:
      - home:/root
      - src:/src
      - /c/Users/yarmand/src:/src/host
      - opt:/opt
      - .:/docker-dev-env
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - "9022:22"


