version: "3"
volumes:
  home:
  src:
  opt:

services:
  devenv:
    build:
      context: .
    volumes:
      - home:/root
      - src:/src
      - /c:/mnt/c
      - opt:/opt
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    ports:
      - "9022:22"


