version: "3"

services:
  devenv:
    volumes:
      - home:/root
      - src:/src
      - opt:/opt
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
      - /Users/yarmand:/Users/yarmand
    ports:
      - "9022:22"
