name: Docker Build and Publish

on:
  push:
    paths: 
      - Dockerfile

jobs:
  docker:
    env:
      IMAGE: yarmand/docker-dev-env/general
      TAG: ${{github.sha}}
      USERNAME: ${{ secrets.GITHUB_USERNAME }}
      PASSWORD: ${{ secrets.GITHUB_PERSONAL_TOKEN }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/${IMAGE}:${TAG}
    - name: docker login
      run: docker login -u ${USERNAME} -p ${PASSWORD} docker.pkg.github.com
    - name: push image
      run: docker push docker.pkg.github.com/${IMAGE}:${TAG}
    - name: tag latest
      run: docker tag docker.pkg.github.com/${IMAGE}:${TAG} docker.pkg.github.com/${IMAGE}:latest
    - name: push latest
      run: docker push docker.pkg.github.com/${IMAGE}:latest
    - name: docker logout
      run: docker logout docker.pkg.github.com
      if: always()
